/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const git_blame: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => any;
export const git_log: (a: number, b: number, c: number, d: number, e: number) => any;
export const git_remote_nostr_helper_url: (a: number, b: number) => [number, number, number, number];
export const git_remote_transport: (a: number, b: number) => [number, number, number, number];
export const normalize_nostr_remote: (a: number, b: number) => [number, number, number, number];
export const normalize_p2p_remote: (a: number, b: number) => [number, number, number, number];
export const nostr_remote_to_p2p: (a: number, b: number) => [number, number, number, number];
export const p2p_remote_to_nostr: (a: number, b: number) => [number, number, number, number];
export const __wbg_wasmdag_free: (a: number, b: number) => void;
export const extractBridgeRoundTripStartMs: (a: any) => [number, bigint, number, number];
export const stampBridgeRoundTripTag: (a: any, b: bigint) => [number, number, number];
export const wasmdag_canonical_ids: (a: number) => [number, number];
export const wasmdag_insert: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmdag_new: (a: number, b: number) => [number, number, number];
export const wasmdag_tip_ids: (a: number) => [number, number];
export const rustsecp256k1_v0_10_0_default_error_callback_fn: (a: number, b: number) => void;
export const rustsecp256k1_v0_10_0_default_illegal_callback_fn: (a: number, b: number) => void;
export const rustsecp256k1_v0_10_0_context_destroy: (a: number) => void;
export const rustsecp256k1_v0_10_0_context_create: (a: number) => number;
export const wasm_bindgen_ab874b650d7c13e9___convert__closures_____invoke___wasm_bindgen_ab874b650d7c13e9___JsValue__core_f0fd674eaa06beef___result__Result_____wasm_bindgen_ab874b650d7c13e9___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_ab874b650d7c13e9___convert__closures_____invoke___js_sys_259eee8e32a44776___Function_fn_wasm_bindgen_ab874b650d7c13e9___JsValue_____wasm_bindgen_ab874b650d7c13e9___sys__Undefined___js_sys_259eee8e32a44776___Function_fn_wasm_bindgen_ab874b650d7c13e9___JsValue_____wasm_bindgen_ab874b650d7c13e9___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
